import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Button from '@mui/material/Button';
import { FaDiscord } from 'react-icons/fa/';
import Tooltip from '@mui/material/Tooltip';
import { RiNumber1 } from 'react-icons/ri';
import { RiNumber2 } from 'react-icons/ri';
import { RiNumber3 } from 'react-icons/ri';
import { RiNumber4 } from 'react-icons/ri';

import React from 'react'
import ReactPlayer from 'react-player/youtube'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CSF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='-mt-40'>

        <div className='pt-32 bg-cover bg-center px-5 lg:px-0' style={{ backgroundImage: `url("/images/headerImg1.png")` }}>
          <div className='flex max-w-screen-xl mx-auto items-center border-b-8 border-black'>
            <div className='flex w-full items-center justify-between text-white pt-48 pb-10 md:pb-28 lg:pb-40 gap-0'>
              <h1 className='text-4xl font-light text-left mb-4 pt-0 w-1/2'>The <span className='font-bold'>Deforestation Impacts Calculator</span> is a tool to assess the social and environmental damage caused by forest logging in the Amazon</h1>
              <div className='flex mx-auto'>
                <Button className='bg-blue-500 py-4 px-8' variant="contained" color="primary" size="large" href="/" target="_blank">CALCULATOR</Button>
              </div>
            </div>
          </div>
        </div>

        <h1 className='text-4xl font-bold p-10 border-b-8 border-black'>Como funciona</h1>

        <div className='flex flex-col md:flex-row mx-4 md:mx-auto pt-0 justify-between items-center gap-10 md:gap-0'>
          <div className='w-full md:w-1/2 p-10 border-r-8 border-black'>

            <div className='mb-4'>
              <p>Você pode incluir algumas informações sobre o contexto para que a calculadora estime o valor dos impactos de forma mais precisa

              A localização define outras variáveis como:</p>
              <div className='mt-4'>
                <ul>

                  <li>-Densidade e tamanho da população afetada</li>

                  <li>-Média de consumo de peixe</li>

                  <li>-Custo de transporte para recuperação de áreas</li>

                  <li>-Tipo de garimpo</li>

                </ul>
              </div>

              <p className='mt-4'>Caso não tenha informações específicas, não tem problema, serão incluídos automaticamente valores médios de contexto e impacto e resultados e suas explicações serão gerados na sequencia.</p>

            </div>
          
          </div>
          <div className='w-full md:w-1/2 ml-0 md:ml-0 p-0 border-0 shadow-md'>
            <div className='bg-cover bg-center shadow-none bg-black'></div>
          </div>
        </div>

        <h1 className='text-4xl font-bold p-10 border-t-8 border-black'>Entenda os impactos do desmatamento</h1>        

        <div className='mt-0 pt-0 pb-0 px-4 md:px-0 border-y-8 border-black'>

          <div className='mx-auto p-0'>

            <div className='flex justify-between p-0 gap-0'>

              <div className="flex flex-col justify-between bg-white border-0 p-0 gap-4 shadow-none w-1/2 border-r-8 border-black">
                <div>
                  <img className='w-24 mx-auto pt-0' src="/images/deforestation.svg" />
                  <div className='text-xl font-bold mt-0 border-b border-black px-4 py-4 text-center'>Restauração</div>
                </div>
                <div className='text-center px-6'>
                  Áreas são abertas para escavação e para a construção de infraestrutura, como estradas e pistas de pouso
                </div>
                <div className='p-4 text-center w-full'><Button className='w-full py-2 px-4' variant="outlined" color="primary" size="medium" href="/" target="_blank">Leia mais</Button></div>
              </div>


              <div className="flex flex-col justify-between bg-white border-0 p-0 gap-4 shadow-none w-1/2">
                <div>
                  <img className='w-24 mx-auto pt-0' src="/images/contamination.svg" />
                  <div className='text-xl font-bold mt-0 border-b border-black px-4 py-4 text-center'>Serviços ecossistêmicos</div>
                </div>
                <div className='text-center px-6'>
                O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos
                </div>
                <div className='p-4 text-center w-full'><Button className='w-full py-2 px-4' variant="outlined" color="primary" size="medium" href="/" target="_blank">Leia mais</Button></div>
              </div>
              
            </div>
          </div>

        </div>

      </main>
    </>
  )
}
