import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Button from '@mui/material/Button';
import { FaDiscord } from 'react-icons/fa/';
import Tooltip from '@mui/material/Tooltip';
import { RiNumber1 } from 'react-icons/ri';
import { RiNumber2 } from 'react-icons/ri';
import { RiNumber3 } from 'react-icons/ri';
import { RiNumber4 } from 'react-icons/ri';

import React from 'react'
import ReactPlayer from 'react-player/youtube'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CSF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='-mt-40'>

        <div className='py-6 bg-cover bg-center px-5 lg:px-0' style={{ backgroundImage: `url("/images/headerImg1.png")` }}>
          <div className='flex max-w-screen-lg mx-auto items-center'>
            <div className='flex flex-col w-full items-center text-white pt-44 pb-10 md:pb-28 lg:pb-40 gap-16'>
              <h1 className='text-5xl font-bold text-center mb-4 pt-10'>Impactos do garimpo ilegal de ouro</h1>
              <div className='flex'>
                <Button className='bg-blue-500 py-4 px-8' variant="contained" color="primary" size="large" href="/" target="_blank">CALCULADORA</Button>
              </div>
            </div>
          </div>
        </div>

        <div className='flex flex-col md:flex-row max-w-screen-lg mx-4 md:mx-auto pt-20 justify-between items-start gap-10 md:gap-10'>
          <div className='w-full md:w-1/2'>

            <h1 className='text-4xl font-bold mb-8'>Introdução</h1>

            <p className='mb-4'>A calculadora de impactos é fruto de uma parceria entre CSF e MPF, uma ferramenta analítica e pedagógica que descreve os impactos do garimpo ilegal de ouro, seus valores monetários e o passo-a-passo para sua mensuração.</p>
          
          </div>
          <div className='w-full md:w-1/2 ml-0 md:ml-10 p-4 border shadow-md'>
            <div className='bg-cover bg-center shadow-lg h-[250px]' style={{ backgroundImage: `url("/images/video.png")` }}></div>
          </div>
        </div>
        

        <div className='mt-20 pt-20 pb-24 px-4 md:px-0 bg-gradient-to-r from-black to-gray-900 border-t-0 border-black'>

          <div className='max-w-screen-lg mx-auto'>
            <div className='text-gray-100 text-left text-3xl md:text-4xl font-bold mb-14'>Entenda os impactos do garimpo</div>

            <div className='container p-0 grid grid-cols-1 sm:grid-cols-1 xl:grid-cols-3 gap-12'>

              <div className="col-span-1 flex flex-col justify-between bg-white rounded-lg border-0 p-0 gap-4 shadow-xl">
                <div>
                  <img className='w-16 mx-auto pt-8' src="/images/deforestation.svg" />
                  <div className='text-xl font-bold mt-0 border-b p-4 text-center'>Desmatamento</div>
                </div>
                <div className='text-center px-6'>
                  Áreas são abertas para escavação e para a construção de infraestrutura, como estradas e pistas de pouso
                </div>
                <div className='p-4 text-center w-full'><Button className='w-full py-2 px-4' variant="outlined" color="primary" size="medium" href="/" target="_blank">Leia mais</Button></div>
              </div>

              <div className="col-span-1 flex flex-col justify-between bg-white rounded-lg border-0 p-0 gap-4 shadow-xl">
                <div>
                  <img className='w-10 mx-auto pt-8' src="/images/river.svg" />
                  <div className='text-xl font-bold mt-0 border-b p-4 text-center'>Assoreamento dos rios</div>
                </div>
                <div className='text-center px-6'>
                  A abertura de cavas gera erosão e assoreamento, enquanto balsas geram sedimentação. Como consequência, há uma piora na qualidade das águas.
                </div>
                <div className='p-4 text-center w-full'><Button className='w-full py-2 px-4' variant="outlined" color="primary" size="medium" href="/" target="_blank">Leia mais</Button></div>
              </div>

              <div className="col-span-1 flex flex-col justify-between bg-white rounded-lg border-0 p-0 gap-4 shadow-xl">
                <div>
                  <img className='w-10 mx-auto pt-8' src="/images/contamination.svg" />
                  <div className='text-xl font-bold mt-0 border-b p-4 text-center'>Contaminação por mercurio</div>
                </div>
                <div className='text-center px-6'>
                O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos
                </div>
                <div className='p-4 text-center w-full'><Button className='w-full py-2 px-4' variant="outlined" color="primary" size="medium" href="/" target="_blank">Leia mais</Button></div>
              </div>
              
            </div>
          </div>

        </div>

        <div className='mt-0 pt-20 pb-32 px-4 md:px-0 bg-gradient-to-r from-gray-50 to-gray-50 border-t-0 border-black'>

          <div className='max-w-screen-lg mx-auto'>
            <div className='text-left text-3xl md:text-4xl font-bold mb-14'>Saiba mais</div>

            <div className='container mx-auto p-0 grid grid-cols-1 sm:grid-cols-1 xl:grid-cols-2 gap-12'>

              <div className="col-span-1 flex bg-white rounded-lg p-0 gap-4 shadow-lg">
                <div className='flex w-1/3 rounded-tl-lg rounded-bl-lg bg-cover bg-center' style={{ backgroundImage: `url("/images/img1.png")` }}></div>
                <div className='flex w-2/3 flex-col p-4 gap-4'>
                  <div className='text-xl font-bold mt-2 border-b border-gray-400 pb-2'>Mapa do garimpo</div>
                  <div className='mb-0'>
                    O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos.
                  </div>
                  <div className='text-sm mb-2 text-blue-600'>continue lendo...</div>
                </div>
              </div>

              <div className="col-span-1 flex bg-white rounded-lg p-0 gap-4 shadow-lg">
                <div className='flex w-1/3 rounded-tl-lg rounded-bl-lg bg-cover bg-center' style={{ backgroundImage: `url("/images/img2.png")` }}></div>
                <div className='flex w-2/3 flex-col p-4 gap-4'>
                  <div className='text-xl font-bold mt-2 border-b border-gray-400 pb-2'>Artigos científicos</div>
                  <div className='mb-0'>
                    O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos.
                  </div>
                  <div className='text-sm mb-2 text-blue-600'>continue lendo...</div>
                </div>
              </div>

              <div className="col-span-1 flex bg-white rounded-lg p-0 gap-4 shadow-lg">
                <div className='flex w-1/3 rounded-tl-lg rounded-bl-lg bg-cover bg-center' style={{ backgroundImage: `url("/images/img3.png")` }}></div>
                <div className='flex w-2/3 flex-col p-4 gap-4'>
                  <div className='text-xl font-bold mt-2 border-b border-gray-400 pb-2'>Histórias de uso</div>
                  <div className='mb-0'>
                    O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos.
                  </div>
                  <div className='text-sm mb-2 text-blue-600'>continue lendo...</div>
                </div>
              </div>

              <div className="col-span-1 flex bg-white rounded-lg p-0 gap-4 shadow-lg">
                <div className='flex w-1/3 rounded-tl-lg rounded-bl-lg bg-cover bg-center' style={{ backgroundImage: `url("/images/img4.png")` }}></div>
                <div className='flex w-2/3 flex-col p-4 gap-4'>
                  <div className='text-xl font-bold mt-2 border-b border-gray-400 pb-2'>Métodos de valoração</div>
                  <div className='mb-0'>
                    O mercúrio despejado pelo garimpo gera impactos sobre o ambiente e sobre a saúde humana, como sintomas neuropsicológicos, cognitivos e cardíacos.
                  </div>
                  <div className='text-sm mb-2 text-blue-600'>continue lendo...</div>
                </div>
              </div>

            </div>

          </div>

        </div>

      </main>
    </>
  )
}
